# Generated by Django 5.0.2 on 2024-05-14 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=500)),
                ('read', models.BooleanField(blank=True, default=False, null=True)),
                ('url_sufix', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('Account', 'Account'), ('Likes', 'Likes'), ('Bookings', 'Bookings'), ('Reviews', 'Reviews')], max_length=10)),
                ('notification_from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
