# Generated by Django 5.0.2 on 2024-05-14 19:41

import datetime
import django.core.validators
import django.db.models.deletion
import reviewee_app.booking.model_helpers
import reviewee_app.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 5, 14))])),
                ('first_name', models.CharField(max_length=32, validators=[reviewee_app.common.validators.only_letters_and_spaces_values_validator])),
                ('last_name', models.CharField(max_length=32, validators=[reviewee_app.common.validators.only_letters_and_spaces_values_validator])),
                ('email', models.EmailField(max_length=120)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('confirmation_code', models.CharField(blank=True, default=reviewee_app.booking.model_helpers.generate_random_confirmation_code, editable=False, max_length=6)),
                ('canceled', models.BooleanField(blank=True, default=False)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('rooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('nights', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)])),
                ('hotel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='place.hotel')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestaurantBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 5, 14))])),
                ('first_name', models.CharField(max_length=32, validators=[reviewee_app.common.validators.only_letters_and_spaces_values_validator])),
                ('last_name', models.CharField(max_length=32, validators=[reviewee_app.common.validators.only_letters_and_spaces_values_validator])),
                ('email', models.EmailField(max_length=120)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('confirmation_code', models.CharField(blank=True, default=reviewee_app.booking.model_helpers.generate_random_confirmation_code, editable=False, max_length=6)),
                ('canceled', models.BooleanField(blank=True, default=False)),
                ('active', models.BooleanField(blank=True, default=True)),
                ('booking_time', models.TimeField(choices=[(datetime.time(0, 0), '00:00'), (datetime.time(0, 30), '00:30'), (datetime.time(1, 0), '01:00'), (datetime.time(1, 30), '01:30'), (datetime.time(2, 0), '02:00'), (datetime.time(2, 30), '02:30'), (datetime.time(3, 0), '03:00'), (datetime.time(3, 30), '03:30'), (datetime.time(4, 0), '04:00'), (datetime.time(4, 30), '04:30'), (datetime.time(5, 0), '05:00'), (datetime.time(5, 30), '05:30'), (datetime.time(6, 0), '06:00'), (datetime.time(6, 30), '06:30'), (datetime.time(7, 0), '07:00'), (datetime.time(7, 30), '07:30'), (datetime.time(8, 0), '08:00'), (datetime.time(8, 30), '08:30'), (datetime.time(9, 0), '09:00'), (datetime.time(9, 30), '09:30'), (datetime.time(10, 0), '10:00'), (datetime.time(10, 30), '10:30'), (datetime.time(11, 0), '11:00'), (datetime.time(11, 30), '11:30'), (datetime.time(12, 0), '12:00'), (datetime.time(12, 30), '12:30'), (datetime.time(13, 0), '13:00'), (datetime.time(13, 30), '13:30'), (datetime.time(14, 0), '14:00'), (datetime.time(14, 30), '14:30'), (datetime.time(15, 0), '15:00'), (datetime.time(15, 30), '15:30'), (datetime.time(16, 0), '16:00'), (datetime.time(16, 30), '16:30'), (datetime.time(17, 0), '17:00'), (datetime.time(17, 30), '17:30'), (datetime.time(18, 0), '18:00'), (datetime.time(18, 30), '18:30'), (datetime.time(19, 0), '19:00'), (datetime.time(19, 30), '19:30'), (datetime.time(20, 0), '20:00'), (datetime.time(20, 30), '20:30'), (datetime.time(21, 0), '21:00'), (datetime.time(21, 30), '21:30'), (datetime.time(22, 0), '22:00'), (datetime.time(22, 30), '22:30'), (datetime.time(23, 0), '23:00'), (datetime.time(23, 30), '23:30')])),
                ('people', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Minimum 1 person required for booking.'), django.core.validators.MaxValueValidator(6, 'Maximum of 6 people allowed per booking.')])),
                ('restaurant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='place.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
