# Generated by Django 5.0.2 on 2024-04-02 23:11

import datetime
import django.core.validators
import django.db.models.deletion
import reviewee_app.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('place', '0003_alter_hotel_description_alter_restaurant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantbooking',
            name='confirmation_code',
            field=models.CharField(blank=True, default='OZikD', editable=False, max_length=5),
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 4, 2))])),
                ('first_name', models.CharField(max_length=32, validators=[reviewee_app.common.validators.only_letters_and_spaces_values_validator])),
                ('last_name', models.CharField(max_length=32, validators=[reviewee_app.common.validators.only_letters_and_spaces_values_validator])),
                ('email', models.EmailField(max_length=120)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('confirmation_code', models.CharField(blank=True, default='OZikD', editable=False, max_length=5)),
                ('rooms', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('nights', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(14)])),
                ('hotel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='place.hotel')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
