# Generated by Django 5.0.2 on 2024-04-24 22:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_hotelbooking_date_alter_restaurantbooking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 4, 24))]),
        ),
        migrations.AlterField(
            model_name='restaurantbooking',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 4, 24))]),
        ),
    ]
