# Generated by Django 5.0.2 on 2024-04-03 01:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_restaurantbooking_confirmation_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='canceled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='restaurantbooking',
            name='canceled',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='confirmation_code',
            field=models.CharField(blank=True, default='vgAqB', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 4, 3))]),
        ),
        migrations.AlterField(
            model_name='restaurantbooking',
            name='confirmation_code',
            field=models.CharField(blank=True, default='vgAqB', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='restaurantbooking',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2024, 4, 3))]),
        ),
    ]
