# Generated by Django 5.0.2 on 2024-04-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_hotelbooking_canceled_restaurantbooking_canceled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='restaurantbooking',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='confirmation_code',
            field=models.CharField(blank=True, default='GfAAp', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='restaurantbooking',
            name='confirmation_code',
            field=models.CharField(blank=True, default='GfAAp', editable=False, max_length=5),
        ),
    ]
