# Generated by Django 5.0.2 on 2024-04-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_hotelbooking_active_restaurantbooking_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='confirmation_code',
            field=models.CharField(blank=True, default='MqUwt', editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='restaurantbooking',
            name='confirmation_code',
            field=models.CharField(blank=True, default='MqUwt', editable=False, max_length=5),
        ),
    ]
