version: '3.4'

services:

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"

  web:
    image: reviewee
    build: .
    command: gunicorn reviewee_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./staticfiles:/tmp/Reviewee/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./.env


#  postgres:
#    image: postgres
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_PASSWORD: postgresPASS
#      POSTGRES_USER: postgres
#      POSTGRES_DB: reviewee_db
#      PGDATA: /var/lib/postgresql/data/pgdata
#    volumes:
#      - ./postgresql:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - web
