# Generated by Django 5.0.2 on 2024-03-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelreview',
            name='review_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/review/photos'),
        ),
        migrations.AddField(
            model_name='restaurantreview',
            name='review_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/review/photos'),
        ),
    ]
