# Generated by Django 5.0.2 on 2024-03-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_hotel_description_restaurant_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(),
        ),
    ]
