# Generated by Django 5.0.2 on 2024-04-18 14:28

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import reviewee_app.account.managers
import reviewee_app.common.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', reviewee_app.account.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserBusinessProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='business_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_logo', models.URLField(blank=True, max_length=220, null=True)),
                ('business_name', models.CharField(blank=True, max_length=120, null=True, validators=[reviewee_app.common.validators.only_letters_and_spaces_values_validator])),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(max_length=50, validators=[reviewee_app.common.validators.check_country_name_validator])),
                ('city', models.CharField(max_length=50, validators=[reviewee_app.common.validators.only_letters_and_spaces_values_validator])),
                ('address_line', models.CharField(max_length=120)),
                ('postcode', models.CharField(max_length=10, validators=[reviewee_app.common.validators.alphanumeric_and_spaces_values_validator])),
                ('telephone', models.CharField(max_length=11, validators=[reviewee_app.common.validators.telephone_number_validator])),
                ('website', models.URLField(blank=True, max_length=220, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUserProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('owner', models.BooleanField(blank=True, default=False, null=True)),
                ('username', models.CharField(blank=True, max_length=32, null=True, validators=[reviewee_app.common.validators.alphanumeric_and_dashes_validator])),
                ('first_name', models.CharField(blank=True, max_length=120, null=True, validators=[reviewee_app.common.validators.only_letters_and_spaces_values_validator])),
                ('last_name', models.CharField(blank=True, max_length=120, null=True, validators=[reviewee_app.common.validators.only_letters_and_spaces_values_validator])),
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
