# Generated by Django 5.0.4 on 2024-04-10 13:22

import reviewee_app.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserbusinessprofile',
            name='telephone',
            field=models.CharField(default='07111111111', max_length=11, validators=[reviewee_app.common.validators.telephone_number_validator]),
        ),
        migrations.AddField(
            model_name='customuserbusinessprofile',
            name='website',
            field=models.URLField(blank=True, default='https://www.google.com', max_length=220, null=True),
        ),
    ]
