# Generated by Django 5.0.4 on 2024-04-10 13:24

import reviewee_app.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuserbusinessprofile_telephone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserbusinessprofile',
            name='telephone',
            field=models.CharField(max_length=11, validators=[reviewee_app.common.validators.telephone_number_validator]),
        ),
        migrations.AlterField(
            model_name='customuserbusinessprofile',
            name='website',
            field=models.URLField(blank=True, max_length=220, null=True),
        ),
    ]
