# Generated by Django 5.0.2 on 2024-03-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='owner',
            field=models.BooleanField(default=False),
        ),
    ]
