# Generated by Django 5.0.2 on 2024-03-06 18:23

import django.db.models.deletion
import reviewee_app.common.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuserprofile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserBusinessProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='business_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_name', models.CharField(blank=True, max_length=120, null=True, validators=[reviewee_app.common.validators.only_letters_and_spaces_values_validator])),
                ('country', models.CharField(max_length=50, validators=[reviewee_app.common.validators.check_country_name_validator])),
                ('city', models.CharField(max_length=50, validators=[reviewee_app.common.validators.only_letters_and_spaces_values_validator])),
                ('address_line', models.CharField(max_length=120)),
                ('post_code', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
