# Generated by Django 5.0.2 on 2024-03-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuserbusinessprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuserbusinessprofile',
            old_name='post_code',
            new_name='postcode',
        ),
    ]
