# Generated by Django 5.0.2 on 2024-03-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_post_code_customuserbusinessprofile_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='owner',
            field=models.BooleanField(editable=False),
        ),
    ]
