# Generated by Django 5.0.2 on 2024-03-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuserprofile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='owner',
            field=models.BooleanField(blank=True),
        ),
    ]
