# Generated by Django 5.0.2 on 2024-03-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_customuserbusinessprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserbusinessprofile',
            name='business_logo',
            field=models.URLField(blank=True, max_length=220, null=True),
        ),
    ]
