# Generated by Django 5.0.2 on 2024-03-12 18:01

import reviewee_app.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_customuserbusinessprofile_business_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserbusinessprofile',
            name='postcode',
            field=models.CharField(max_length=10, validators=[reviewee_app.common.validators.alphanumeric_and_spaces_values_validator]),
        ),
    ]
