# Generated by Django 5.0.2 on 2024-03-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_customuserbusinessprofile_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserbusinessprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
